services:
  frontend:
    build:
      context: .
    container_name: ${COMPOSE_PROJECT_NAME}_mk8dxtournament
    restart: unless-stopped
    volumes:
      - ./public:/app/public
    ports:
      - "3000:3000"
